In [10]:
import torch
import torch.nn as nn
import numpy as np
import tiktoken

In [1]:
text = "this is an example sentence to see the input into the encoder"

In [20]:
class Config:
    def __init__(
        self,
        layers =6, 
        v_size = 50257,
        dim = 512,
        heads = 12,
    ):
        self.layers = 6
        self.vocab = v_size
        self.dim = dim
        self.heads = heads

In [3]:
class Tokenizing:
    def __init__(self):
        self.enc = tiktoken.get_encoding("gpt2")

    def encode(self, txt):
        return self.enc.encode(txt)

    def decode(self, ints):
        return self.enc.decode(ints)

In [4]:
class EncoderEmbedding(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.word_embeddings = nn.Embeddings(config.vocab, config.dim)
        self.position_embeddings = torch.ones((0, config.dim))
        
    def forward(self, ints):
        
        return 
        


SyntaxError: incomplete input (1062673257.py, line 9)

In [11]:
class SinusoidalPositionalEncoding(nn.Module):
    def __init__(self, config):
        # tensor -> 512, 10000
        pos = torch.zeros(config.vocab, config.dim)
        p = torch.arange(0, config.vocab).unsqueeze(1)
        d = 10000**(2*torch.arange(0, config.vocab)/config.dim)
        
        new = p/d
        pos[0::2] = torch.sin(new[0::2)


        
    
    

In [44]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [60]:
pe.shape, terms.shape

(torch.Size([10, 512]), torch.Size([10, 512]))

In [113]:
def positional_encoding(seq_len, d_model, base):
    pe = torch.zeros(seq_len, d_model)
    pos = torch.arange(0, seq_len, dtype=torch.float).unsqueeze(1) #(seq_len, 1)
    
    div_terms = base**((torch.arange(0, d_model, 2)).float()/d_model).unsqueeze(0) #(1, d_model/2)

    terms = pos/div_terms #(seq_len, d_model/2)

    print(terms.shape)
   # okay so if we have 512 embeddings space -> range will be till 256, 0 for sin and 0 for cos and then 1 for sin and 1 for cosine 
    pe[:, 0::2] = torch.sin(terms[:, :])
    pe[:, 1::2] = torch.cos(terms[:, :])
    
    return pe

pos = positional_encoding(8, 512, 10000)
pos[1]

torch.Size([8, 256])


tensor([8.4147e-01, 5.4030e-01, 8.2186e-01, 5.6969e-01, 8.0196e-01, 5.9738e-01,
        7.8189e-01, 6.2342e-01, 7.6172e-01, 6.4791e-01, 7.4154e-01, 6.7091e-01,
        7.2141e-01, 6.9250e-01, 7.0140e-01, 7.1276e-01, 6.8156e-01, 7.3176e-01,
        6.6193e-01, 7.4956e-01, 6.4256e-01, 7.6624e-01, 6.2347e-01, 7.8185e-01,
        6.0469e-01, 7.9646e-01, 5.8626e-01, 8.1012e-01, 5.6818e-01, 8.2290e-01,
        5.5048e-01, 8.3485e-01, 5.3317e-01, 8.4601e-01, 5.1625e-01, 8.5644e-01,
        4.9974e-01, 8.6618e-01, 4.8364e-01, 8.7527e-01, 4.6795e-01, 8.8376e-01,
        4.5267e-01, 8.9168e-01, 4.3781e-01, 8.9907e-01, 4.2335e-01, 9.0596e-01,
        4.0931e-01, 9.1240e-01, 3.9567e-01, 9.1839e-01, 3.8242e-01, 9.2399e-01,
        3.6957e-01, 9.2920e-01, 3.5711e-01, 9.3406e-01, 3.4503e-01, 9.3859e-01,
        3.3332e-01, 9.4281e-01, 3.2197e-01, 9.4675e-01, 3.1098e-01, 9.5042e-01,
        3.0034e-01, 9.5383e-01, 2.9004e-01, 9.5701e-01, 2.8008e-01, 9.5998e-01,
        2.7043e-01, 9.6274e-01, 2.6110e-

In [77]:
terms[0, 0]

tensor(0.)

In [88]:
pe = torch.zeros(8, 512)

pos = torch.arange(8).unsqueeze(1) # 8, 1
div_terms = 10000**((torch.arange(0,512)*2)/512).unsqueeze(0) # 1, 32

terms = pos/div_terms

pe[:, 0::2] = torch.sin(terms[:, 0::2])
pe[:, 1::2]= torch.cos(terms[:, 1::2])
terms[2]


tensor([2.0000e+00, 1.9293e+00, 1.8611e+00, 1.7954e+00, 1.7319e+00, 1.6707e+00,
        1.6117e+00, 1.5547e+00, 1.4998e+00, 1.4468e+00, 1.3957e+00, 1.3463e+00,
        1.2988e+00, 1.2529e+00, 1.2086e+00, 1.1659e+00, 1.1247e+00, 1.0849e+00,
        1.0466e+00, 1.0096e+00, 9.7394e-01, 9.3952e-01, 9.0632e-01, 8.7429e-01,
        8.4339e-01, 8.1359e-01, 7.8484e-01, 7.5710e-01, 7.3035e-01, 7.0454e-01,
        6.7964e-01, 6.5562e-01, 6.3246e-01, 6.1011e-01, 5.8855e-01, 5.6775e-01,
        5.4768e-01, 5.2833e-01, 5.0966e-01, 4.9165e-01, 4.7427e-01, 4.5751e-01,
        4.4135e-01, 4.2575e-01, 4.1071e-01, 3.9619e-01, 3.8219e-01, 3.6868e-01,
        3.5566e-01, 3.4309e-01, 3.3096e-01, 3.1927e-01, 3.0799e-01, 2.9710e-01,
        2.8660e-01, 2.7647e-01, 2.6670e-01, 2.5728e-01, 2.4819e-01, 2.3942e-01,
        2.3096e-01, 2.2279e-01, 2.1492e-01, 2.0733e-01, 2.0000e-01, 1.9293e-01,
        1.8611e-01, 1.7954e-01, 1.7319e-01, 1.6707e-01, 1.6117e-01, 1.5547e-01,
        1.4998e-01, 1.4468e-01, 1.3957e-

In [76]:
torch.arange(0,10) * 2

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
tokenizer = Tokenizing()
ints = tokenizer.encode(text)

In [9]:
ints

[5661, 318, 281, 1672, 6827, 284, 766, 262, 5128, 656, 262, 2207, 12342]

In [26]:
torch.exp(torch.tensor([1]))

tensor([2.7183])

In [200]:
import numpy as np

def positional_encoding(seq_len, d_model, base=10000.0):
    """
    Return PE of shape (seq_len, d_model) using sin/cos formulation.
    Odd d_model -> last column is sin.
    """
    pe = np.zeros((seq_len, d_model), "float")

    position = np.arange(0, seq_len)[:, np.newaxis]# seq_len, 1
    div_terms = (base**(np.arange(0, d_model, 2)/d_model))[np.newaxis, :]

    terms = position/div_terms

    print(pe.shape, terms.shape)

    pe[: ,0::2] = np.sin(terms)
    pe[:, 1::2] = np.cos(terms)
    
    return pe

def add_positional_encoding(x, base=10000.0):
    """
    Add PE to input x of shape (B, T, d_model); return same shape.
    """
    B, T, d_model = x
    B = np.zeros((B, 1,1))

    pe = positional_encoding(T, d_model, base)
    print(pe.shape)
    
    return B + pe  

In [201]:
x = add_positional_encoding((2, 8, 11))

(8, 11) (8, 6)


ValueError: could not broadcast input array from shape (8,6) into shape (8,5)

In [192]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [203]:
z = np.arange(7)
z[0::2]

array([0, 2, 4, 6])